--------------------------------------------------------
--  File created - Thursday-November-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "ILQAR"."EMPLOYEE" 
   (	"EMPNO" NUMBER, 
	"EMPNAME" VARCHAR2(20 BYTE), 
	"EMPSURNAME" VARCHAR2(20 BYTE), 
	"EMPSALARY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ILQAR.EMPLOYEE
SET DEFINE OFF;
Insert into ILQAR.EMPLOYEE (EMPNO,EMPNAME,EMPSURNAME,EMPSALARY) values (1,'Gunshan','Safarova',10000);
Insert into ILQAR.EMPLOYEE (EMPNO,EMPNAME,EMPSURNAME,EMPSALARY) values (121,'Vali','Ali',6565);
Insert into ILQAR.EMPLOYEE (EMPNO,EMPNAME,EMPSURNAME,EMPSALARY) values (1997,'Ayshan','Safarova1500',1500);
Insert into ILQAR.EMPLOYEE (EMPNO,EMPNAME,EMPSURNAME,EMPSALARY) values (666,'666','666',666);
Insert into ILQAR.EMPLOYEE (EMPNO,EMPNAME,EMPSURNAME,EMPSALARY) values (0,'Samir','Akbar',-100);
--------------------------------------------------------
--  DDL for Index SYS_C0013567
--------------------------------------------------------

  CREATE UNIQUE INDEX "ILQAR"."SYS_C0013567" ON "ILQAR"."EMPLOYEE" ("EMPNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "ILQAR"."EMPLOYEE" ADD PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ILQAR"."EMPLOYEE" MODIFY ("EMPNAME" NOT NULL ENABLE);
